// Generated by CoffeeScript 2.2.3
(function() {
  var age, ages, child, yearsOld;

  yearsOld = {
    max: 10,
    ida: 9,
    tim: 11
  };

  ages = (function() {
    var results;
    results = [];
    for (child in yearsOld) {
      age = yearsOld[child];
      results.push("");
    }
    return results;
  })();

}).call(this);
